# Generated by Django 5.2.3 on 2025-06-27 16:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exames', '0001_initial'),
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_glicose', models.FloatField(verbose_name='Valor da Glicose (mg/dL)')),
                ('tipo_medicao', models.CharField(choices=[('', 'Tipo de Medição'), ('pre_prandial', 'Pré-Prandial'), ('pos_prandial_1h', 'Pós-Prandial 1 Hora'), ('pos_pandrial_2h', 'Pós-Pandrial 2 Horas'), ('jejum', 'Jejum'), ('aleatoria', 'Aleatória')], max_length=20, verbose_name='Tipo de Medição')),
                ('data_medicao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Medição')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('alimento', models.CharField(blank=True, max_length=150, null=True, verbose_name='Alimento')),
                ('tipo_refeicao', models.CharField(blank=True, choices=[('', 'Tipo de Refeição'), ('cafe_manha', 'Café da Manhã'), ('almoco', 'Almoço'), ('jantar', 'Jantar'), ('lanche_manha', 'Lanche da Manhã'), ('lanche_tarde', 'Lanche da Tarde'), ('ceia', 'Ceia')], max_length=20, null=True, verbose_name='Tipo de Refeição')),
                ('tamanho', models.CharField(blank=True, choices=[('', 'Tamanho das Refeições'), ('pequena', 'Pequena (até 299g)'), ('media', 'Média (300g até 499g)'), ('grande', 'Grande (500 até 800g)')], max_length=20, null=True, verbose_name='Tamanho')),
                ('exame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicoes', to='exames.exame', verbose_name='Exame Relacionado')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.perfil', verbose_name='Perfil')),
            ],
            options={
                'verbose_name_plural': 'Medições',
            },
        ),
    ]
