# Generated by Django 5.2.3 on 2025-11-02 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicao',
            options={'ordering': ['-data_medicao'], 'verbose_name_plural': 'Medições'},
        ),
        migrations.RemoveField(
            model_name='medicao',
            name='alimento',
        ),
        migrations.RemoveField(
            model_name='medicao',
            name='tamanho',
        ),
        migrations.RemoveField(
            model_name='medicao',
            name='tipo_refeicao',
        ),
    ]
