# Dockerfile para Postgres custom com entrypoint embutido
FROM postgres:17.7

RUN --mount=type=secret,id=db_name \
 DB_NAME_FILE=/run/secrets/db_name

RUN --mount=type=secret,id=db_user \
 DB_USER_FILE=/run/secrets/db_user

RUN --mount=type=secret,id=db_password \
 DB_PASSWORD=/run/secrets/db_password

RUN copy ./entrypoint-postgres.sh /usr/local/bin/entrypoint-postgres.sh

# Define como entrypoint principal (substitui o oficial)
ENTRYPOINT ["/usr/local/bin/entrypoint-postgres.sh"]