# Generated by Django 5.2.3 on 2025-06-27 16:49

import datetime
import django.db.models.deletion
import perfis.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('altura', models.FloatField(blank=True, help_text='Altura em CM', null=True, verbose_name='Altura')),
                ('tipo_sanguineo', models.CharField(blank=True, max_length=3, null=True, verbose_name='Tipo Sanguíneo')),
                ('tipo_diabetes', models.CharField(blank=True, choices=[('tipo1', 'Tipo 1'), ('tipo2', 'Tipo 2')], max_length=10, null=True, verbose_name='Tipo Diabetes')),
                ('tempo_diagnostico', models.IntegerField(blank=True, help_text='Ano da Descoberta', null=True, verbose_name='Tempo de Diagnóstico')),
                ('insulina', models.CharField(blank=True, choices=[('sim', 'Sim'), ('não', 'Não')], help_text='Insulina', null=True, verbose_name='Usa Insulina?')),
                ('medicamentos_utilizados', models.TextField(blank=True, null=True, verbose_name='Medicamentos Utilizados')),
                ('alergias', models.TextField(blank=True, null=True, verbose_name='Alergias')),
                ('outras_condicoes', models.TextField(blank=True)),
                ('primeiro_login_completo', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'ordering': ['-data_nascimento'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPesoImc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('peso_kg', models.DecimalField(decimal_places=2, help_text='Peso em Kg', max_digits=5, verbose_name='Peso')),
                ('imc', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfilpeso', to='perfis.perfil')),
            ],
            options={
                'verbose_name': 'Historico Peso Imc',
                'verbose_name_plural': 'Historicos Peso Imc',
                'ordering': ['-peso_kg'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoBioTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField(default=datetime.date.today, editable=False)),
                ('proximo_registro', models.DateField(default=perfis.models.add_tempo, editable=False)),
                ('cintura', models.FloatField(help_text='Cintura em CM', verbose_name='Cintura')),
                ('quadril', models.FloatField(help_text='Quadril em CM', verbose_name='Quadril')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfilbiotipo', to='perfis.perfil')),
            ],
            options={
                'verbose_name': 'Historico Peso Imc',
                'verbose_name_plural': 'Historicos Peso Imc',
                'ordering': ['-data_registro'],
            },
        ),
    ]
