# Generated by Django 5.2.3 on 2025-11-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_alter_perfil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicobiotipo',
            name='braco',
            field=models.FloatField(blank=True, help_text='Circunferência do braco em CM', null=True, verbose_name='Braco'),
        ),
        migrations.AddField(
            model_name='historicobiotipo',
            name='perna',
            field=models.FloatField(blank=True, help_text='Circunferência do perna em CM', null=True, verbose_name='Perna'),
        ),
    ]
