# Generated by Django 5.2.3 on 2025-11-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0003_historicobiotipo_braco_historicobiotipo_perna'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicobiotipo',
            name='abdomen',
            field=models.FloatField(blank=True, help_text='Circunferência abdominal em CM', null=True, verbose_name='Abdomen'),
        ),
        migrations.AlterField(
            model_name='historicobiotipo',
            name='braco',
            field=models.FloatField(blank=True, help_text='Circunferência do braco em CM', null=True, verbose_name='Braço'),
        ),
        migrations.AlterField(
            model_name='historicobiotipo',
            name='perna',
            field=models.FloatField(blank=True, help_text='Circunferência da perna em CM', null=True, verbose_name='Pernas'),
        ),
    ]
