# Generated by Django 6.0b1 on 2025-12-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0004_historicobiotipo_abdomen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='peso_desejado',
            field=models.FloatField(blank=True, help_text='Peso Ideal', null=True, verbose_name='Peso Ideal'),
        ),
        migrations.AlterField(
            model_name='historicobiotipo',
            name='abdomen',
            field=models.FloatField(blank=True, help_text='Circunferência abdominal em CM', null=True, verbose_name='Abdômen'),
        ),
    ]
