# Generated by Django 6.0b1 on 2025-12-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0005_perfil_peso_desejado_alter_historicobiotipo_abdomen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicopesoimc',
            options={'ordering': ['-peso'], 'verbose_name': 'Historico Peso Imc', 'verbose_name_plural': 'Historicos Peso Imc'},
        ),
        migrations.RenameField(
            model_name='historicopesoimc',
            old_name='peso_kg',
            new_name='peso',
        ),
        migrations.AddField(
            model_name='historicopesoimc',
            name='grau_obesidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Grau de Obesidade'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='peso_desejado',
            field=models.FloatField(blank=True, help_text='Peso desejado para alcançar', null=True, verbose_name='Peso Desejado'),
        ),
    ]
