# Generated by Django 6.0b1 on 2026-01-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0006_alter_historicopesoimc_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicobiotipo',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='fotos', verbose_name='Fotos'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
    ]
