# Generated by Django 6.0b1 on 2026-01-24 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0007_historicobiotipo_fotos_alter_perfil_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicobiotipo',
            name='fotos',
        ),
        migrations.CreateModel(
            name='HistoricoBioTipoFotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, help_text='Anexo fotos corporais para comparação', null=True, upload_to='fotos', verbose_name='Foto do Corpo')),
                ('historicobiotipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicobiotipofotos', to='perfis.historicobiotipo')),
            ],
            options={
                'verbose_name': 'Historico Biotipo Foto',
                'ordering': ['-historicobiotipo'],
            },
        ),
    ]
