# Generated by Django 6.0b1 on 2026-01-24 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0008_remove_historicobiotipo_fotos_historicobiotipofotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicobiotipofotos',
            name='historicobiotipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='perfis.historicobiotipo'),
        ),
    ]
