# Generated by Django 5.2.3 on 2025-06-27 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_exame', models.DateField(verbose_name='Data do Exame')),
                ('medico', models.CharField(max_length=100, verbose_name='Médico')),
                ('especialidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialidade do Médico')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('exame_arquivo', models.FileField(blank=True, null=True, upload_to='exames', verbose_name='Arquivo')),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfis.perfil', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Exame',
                'verbose_name_plural': 'Exames',
                'ordering': ['-data_exame'],
            },
        ),
    ]
