# Generated by Django 5.2.3 on 2025-06-27 16:49

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_refeicao', models.CharField(choices=[('cafe_manha', 'Café da Manhã'), ('almoco', 'Almoço'), ('jantar', 'Jantar'), ('lanche_manha', 'Lanche da Manhã'), ('lanche_tarde', 'Lanche da Tarde'), ('ceia', 'Ceia')], max_length=20, verbose_name='Tipo de Refeição')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='titulo')),
                ('cardapio', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Cardápio')),
                ('tag', models.ManyToManyField(blank=True, related_name='tag', to='core.tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name_plural': 'Planos',
                'unique_together': {('tipo_refeicao', 'cardapio')},
            },
        ),
    ]
